{
 "title": "QAHW-6",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "inst",
    "query": {
     "query": "label_values(up{job='device-api'},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RPS (Started) by Handler",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (grpc_method) (rate(grpc_server_started_total{instance=~\"$inst\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS (Handled) by Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (grpc_code) (rate(grpc_server_handled_total{instance=~\"$inst\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gRPC Server Handled Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{instance=~'$inst'}[1m])) by (grpc_method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time by Handler",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handling_seconds_sum{instance=~\"$inst\"})) by (grpc_method) / sum(rate(grpc_server_handling_seconds_count{instance=~\"$inst\"})) by (grpc_method) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go Metrics - CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=\"$inst\", job=\"device-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go Metrics - Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "go_memstats_heap_sys_bytes{instance=\"$inst\", job=\"device-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go Metrics - GC Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "go_gc_duration_seconds_sum{instance=\"$inst\", job=\"device-api\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}